### ISSUE TITLE
Fibers mirrored across axis

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#116]
Hello,

This fiber (supposed to be Left AF) appears to be centrally located in the right place, but is mirrored across the posterior-anterior axis. I am using the most recent TractSeg build on a HPC, starting with a preprocessed dwi image. 

![image](https://user-images.githubusercontent.com/27028726/86408237-9fbead80-bc84-11ea-836f-f94904bc76ee.png)
![image](https://user-images.githubusercontent.com/27028726/86408310-c2e95d00-bc84-11ea-9018-927fae6a98d9.png)
![image](https://user-images.githubusercontent.com/27028726/86408332-cc72c500-bc84-11ea-82de-72e2775cc1bd.png)

Do you know what may be causing this error? I have tried flipping the x and y axes (both individually and at the same time), and rerunning, which leads to mostly empty tracts.

Thanks,
Steven

**Comment by wasserth** [comment]
You are running it on an already preprocessed Human Connectome Project subject? In this case the orientation of the subject should be correct. So the problem should be a visualization problem. You could set tracking format to tck and try to visualize it in Mrtrix mrview. If this looks correct it should be an issue with trk and TrackVis. Since I am not using TrackVis I can not guarantee that result are visualized correctly in every version.

**Comment by smeisler** [comment]
Turns out DWIConvert from sliver was mysteriously flipping my images across the PA axis; updated the DWI Convert code and rerunning everything now and will close if the issue is solved. Thank you for replying.
