### ISSUE TITLE
Mean FA for the whole bundle

### ISSUE THREAD

**Issue by XL258** [MIC-DKFZ/TractSeg#140]
Hello,

Thanks for this great tool. Both TractSeg and Tractometry ran smoothly on my data. 

My problem is that I didn't get any significant result. However, using DTI model and TBSS with the same data showed very broad effects across the whole skeleton. My guess is that our effects are not large enough to survive multiple comparisons (100 positions per bundle and 71 bundles). 

So I wonder how to extract the mean FA for the whole bundle instead of looking at 100 positions. Do you have any suggestion on the insignificant results? Thanks!

**Comment by smeisler** [comment]
I'm not a TractSeg developer, but here are my thoughts:
1) It shouldn't be too difficult to write a script that loads the individual subject tractometry.csv, and save out the means of the columns. Once you do that, it would just be a matter or doing a two-sample t-test (or Mann-Whitney test if these values are not normally distributed) and then correct for multiple comparisons if you are looking at multiple bundles. This is assuming you are doing a two group comparison, and not a correlation.

2) However, I noticed you are looking at 71 bundles (out of TractSeg's 72)! At that point, you would be better off doing a whole-brain kind of method, like TBSS. Unless your hypothesis warrants looking at the 71 bundles (which is unlikely), you aren't doing yourself any favors here. Ideally, you would have picked a few bundles you want to look at based on your hypothesis beforehand, and then only run those. Since looking at your TractSeg results, you are no longer blinded to the trends in the data, and may risk the mistake of saying "I'll keep this bundle because I think it will survive multiple comparisons when I choose fewer bundles", which is not the right way to do science.

3) I would imagine that if you didn't get any significant areas when looking at individual nodes, then you probably won't get any significance when averaging, as differences are probably going to be localized to nodes rather than across the whole tract. Doing a bundle average will bring the different bundle metrics closer together by incorporating the "noise" you often get towards the ends of the bundles when they are more branching.

Best,
Steven

**Comment by smeisler** [comment]
You may benefit from looking at this paper [(Wasserthal et al., 2020)](https://www.nature.com/articles/s41386-020-0691-2 ). It shows how to use TBSS and TractSeg as more targeted approaches.

**Comment by wasserth** [comment]
Thanks @smeisler for this great explanation. I can only agree on this!

**Comment by XL258** [comment]
Thank you very much, @smeisler and @wasserth  for your help and suggestion, and the paper is very helpful to me. As what Steven said, the results are even more insignificant after doing a bundle average.

I have two more questions, (1) is it possible to export (number of) streamlines of individual bundles? (2) Does it make sense to compare numbers of streamlines of the segmented bundles between two groups (as I would like to take into account the crossing-fiber issue)? 

I tried to modify some codes in bin/Tractometry  to export streamlines:

          if args.tracking_format == "trk_legacy":
                streams, hdr = trackvis.read(trk_path)
                streamlines = [s[0] for s in streams]
            else:
                sl_file = nib.streamlines.load(trk_path)
                streamlines = sl_file.streamlines

But the streamlines that I exported are across the whole brain. 

I would appreciate any suggestion or help you could provide.

**Comment by smeisler** [comment]
I imagine that Dipy or similar program could read information from a .tck or .trk file to return streamline count, but I don't think it will be a useful metric. TractSeg uses machine learning to predict individual streamlines, so the number of streamlines is really just determined by how many times you want TractSeg to guess a streamline. The number of streamlines is set to default at 2000 per bundle, so it shouldn't vary between bundles unless TractSeg is having trouble resolving a bundle (can happen with Fornix, CA, sometimes right AF, etc). The Tractometry wiki page suggests setting this number to 5000 per bundle which creates less variability between runs. So, I wouldn't compare the number of streamlines per bundle.

Also, if you look at the bottom of the tractometry wiki, they provide some suggestions about dealing with crossing fibers (using the peaks instead of FA).

**Comment by XL258** [comment]
> I imagine that Dipy or similar program could read information from a .tck or .trk file to return streamline count, but I don't think it will be a useful metric. TractSeg uses machine learning to predict individual streamlines, so the number of streamlines is really just determined by how many times you want TractSeg to guess a streamline. The number of streamlines is set to default at 2000 per bundle, so it shouldn't vary between bundles unless TractSeg is having trouble resolving a bundle (can happen with Fornix, CA, sometimes right AF, etc). The Tractometry wiki page suggests setting this number to 5000 per bundle which reduces variability between runs. So, I wouldn't compare the number of streamlines per bundle.
> 
> Also, if you look at the bottom of the tractometry wiki, they provide some suggestions about dealing with crossing fibers (using the peaks instead of FA).

Thank you very much for your clear explanation and suggestion! That helps me a lot.
