### ISSUE TITLE
How to Interpret Correlation Graphs

### ISSUE THREAD

**Issue by smeisler** [MIC-DKFZ/TractSeg#145]
Hello,

I am having trouble interpreting the results of the correlation graphs. This was made on ~100 subjects using TractSeg 2.2. From what I understand, and please correct me if I am wrong:

1. The alpha FWE, since I am looking at only a single tract, represents the correlative p-threshold after accounting for the 100 node tract comparisons.
2. The correlation coefficient corresponds to the minimum p-val obtained in the tract, not the threshold needed for significance
3. Nodes between red lines represent clusters that reach that correlation

What I do not understand:

1. Is the "metric" y-axis representative of the average FA (or whatever tract metric one is using to correlate against the target)?
2. Is the shaded region surrounding the line SE or a 95% CI, or something else?
3. Are covariates regressed out of this line?

![image](https://user-images.githubusercontent.com/27028726/113441204-e2501a80-93bb-11eb-8a77-84c1fc6ce35e.png)

Thank you for your help,
Steven

**Comment by wasserth** [comment]
Good questions. You are right with your assumptions:  

1: yes  
2: yes (corr.coeff.: the correlation coefficient at the position where the p-value is minimal)  
3: yes
4: yes, the y-axis represents the FA (if you use the FA for tractometry).
5: the shaded area surrounding the line is the 95% confidence interval (it is automatically generated by seaborn lineplot when using the ci argument: https://seaborn.pydata.org/generated/seaborn.lineplot.html )
6: yes (because covariates are regressed out of this line the values might look different from from what you see in your Tractometry csv files)
