### ISSUE TITLE
issue with --preprocessing option

### ISSUE THREAD

**Issue by giulia-berto** [MIC-DKFZ/TractSeg#195]
The `--preprocessing` option seems to still produce not coherent results. In particular, my guess is that TOM_tracking .tck files are not retrieved correctly since peaks.nii.gz seems to be in MNI space while the ending segmentations seem to be in subject's space. This happens both with the master branch and version 2.7.  This was an issue of the past, and you were suggesting to align the dwi before giving it as an input of TractSeg. Is that still the case? Do you advise to avoid the `--preprocessing` option? Thanks!

**Comment by wasserth** [comment]
Would it be possible to share the DWI data of a subject where this is happening? Then I can try to reproduce the issue.

**Comment by giulia-berto** [comment]
Thanks, I've put the data here, let me know if you have issues accessing it.

https://brainlife.io/project/62391ba85d8ab5d5f0429690#object:632b2a9471291bb27f9e296

**Comment by wasserth** [comment]
Thanks for the data. The issue seems more complicated unfortunately. The problem is how the TOMs are transformed from MNI space to subject Space. I am using FSL vecreg for this and this is not working as I expected.  Not sure how fast I will be able to fix it.
For now I would recommend not using the --preprocess option. For this specific dataset for example it is also not necessary. It works well without --preprocess.

**Comment by giulia-berto** [comment]
ok, sounds good. Yes, I noticed that for this data I don't need it, but I was curious if the --preprocessing option was still an issue. I will do the preprocessing in advance if needed then, thanks for looking into this!
