### ISSUE TITLE
Tractometry in native space

### ISSUE THREAD

**Issue by aver123** [MIC-DKFZ/TractSeg#28]
First of all, thanks for this great tool!
One quick question. Following instructions as per https://github.com/MIC-DKFZ/TractSeg/blob/master/resources/Tractometry_documentation.md WITHOUT NORMALIZING TO MNI SPACE will still allow me to get the 20 nodes for each tract (in native space) in all my subjects.
AFQ defines the tracts in native space to ultimately 'project' the tract-profiles in MNI space (I guess). Is there a reason why you are suggesting to run the tractometry in MNI space for display purpose? 
Thanks a lot!!
Amelia

**Comment by aver123** [comment]
sorry, I meant to say for (I guess for display purpose)...... tractometry in MNI space.  :-)

**Comment by wasserth** [comment]
TractSeg works best in MNI space  (generation of tract segmentations and tract orientation maps which are then used for tractography). Therefore it is recommended to first rigidly align your subject with MNI space and then run TractSeg. For running the actual tractography and tractometry it does not matter in which space you are. So you could transform the tract orientation map back to your subject space and then do tractography.
TractSeg also works in non-MNI space as long as the space has the same orientation as MNI space. But I always tested on subjects rigidly aligned to MNI space. So I can guarantee that it works well in that case but do not have so much experience how it behaves in other cases (it will work but quality might be reduced to some degree).
I hope that answered your question, otherwise let me know.
