### ISSUE TITLE
wrong dimension segmentations (146x174x146x72)

### ISSUE THREAD

**Issue by giulia-berto** [MIC-DKFZ/TractSeg#31]
Hi @wasserth,
I've noticed that the 4D .nii.gz segmentations output masks have dimensions (146x174x146x72). I'm using HCP data and TractSeg version v1.9. In the function `scale_input_to_world_shape` there is a scaling to those dimensions, while I guess it should be (145x174x145x72).
`    if resolution == "1.25mm":`
       `     if dataset == "HCP":  # (144,144,144)`
            `    # no resize needed`
           `         return img_utils.pad_4d_image_left(img4d, np.array([1, 15, 1, 0]),`
                                              ` [146, 174, 146, img4d.shape[3]], pad_value=0)  # (146, 174, 146, none)`
Do you have an explanation for this?
Thank you!

**Comment by wasserth** [comment]
Hi,
the original problem was the following: If you resample the HCP image from 1.25mm to 2.5mm resolution you get `[73,87,73]`. When you upsample this back to 1.25mm you get `[146,174,146]`. So unfortunately this is different from what you had in the beginning. Now you would have to remember if you downsampled from a uneven shape and then cut one value if you upsample again. That's what is done in `TractSeg`. For `ExpRunner` I did not bother doing this. If I need the output to be `[145,174,145]` I just do `data = data[:-1, :, :-1, :]`, or use `TractSeg` for inference (using the branch `speed_up` you can do `TractSeg ... --exp_name <your experiment_name>` and use `TractSeg` for inference with your custom experiments instead of doing `ExpRunner --seg/--probs`.
The code for training your own models (`ExpRunner`) is not as polished as the code for using the pretrained models (`TractSeg`) so unfortunately it is a bit more inconvenient to use.
I hope that answered your question.
