### ISSUE TITLE
AFD - Tractometry careful consideration

### ISSUE THREAD

**Issue by chamberm** [MIC-DKFZ/TractSeg#42]
Hi guys,

first of all, congrats on the great tool. Works flawlessly and runs nicely on most datasets I've tested so far. Handles standard and state-of-the-art data (e.g., Connectom generated data) pretty well (>5 shells).

I do however have a small comment/question for future users/devs. regarding the Tractometry option. I see that you provide the option to generate the peak length along the tract (which in some way is a discretized Apparent Fiber Density similar to FBA/AFD analysis in MRtrix). 

The problem with the current Tractometry implementation is that each subject is processed independently and therefore the response function is unique to each participant (which is contradictory to the recommended steps for AFD). Typically, one has to take the average response function (or a single 1 and apply it to the whole group to generate the fods.). This will allow a correct comparison of the amplitudes between subjects (e.g. comparing oranges with oranges). Some other steps would, in theory, be needed as well (i.e. bias field correction on the data before giving it as input to TractSeg or mtnormalise the msmt-csd outputs of TractSeg).

As mentioned by Thijs on the MRtrix forums: "In a way, the response function is the unit of your FOD"

Maybe a word of caution on the wiki page would help future users!

Best,
Max

**Comment by wasserth** [comment]
Hi Max,
thanks for pointing this out. I will update the documentation so anybody using it is aware of this.

**Comment by thijsdhollander** [comment]
> I see that you provide the option to generate the peak length along the tract (which in some way is a discretized Apparent Fiber Density similar to FBA/AFD analysis in MRtrix).

Nice; I didn't know you've built some of these things into the tool/docs, definitely very useful!  The peak length is a tricky one indeed.  It'll be partially proportional to the AFD, as @chamberm mentions indeed, but at the same time (inversely) proportional to the respective FOD lobe width.  The "true" AFD would be the FOD lobe integral.  For the same "true" AFD (i.e. integral), the peak amplitude would for instance be smaller if the lobe is wider, due to e.g. more dispersion.

> each subject is processed independently and therefore the response function is unique to each participant (which is contradictory to the recommended steps for AFD)

Correct indeed, not even "only" for AFD, but also for any outcome or metric of the (single- or multi-tissue) CSD method.

> Typically, one has to take the average response function (or a single 1 and apply it to the whole group to generate the fods.). This will allow a correct comparison of the amplitudes between subjects (e.g. comparing oranges with oranges). Some other steps would, in theory, be needed as well (i.e. bias field correction on the data before giving it as input to TractSeg or mtnormalise the msmt-csd outputs of TractSeg).

Yep, well explained. :+1:  Just to further emphasise this bit for future reference:

> the average response function (or a single 1 and apply it to the whole group to generate the fods.)

...so the most important point is "a single 1" (per tissue type). The "average" bit is not a requirement, but what you'd typically end up doing, because there's no obvious alternative. I'm actually working on an alternative; but the *main* point remains the same: to use a single unique response (per tissue type).  The idea that using the *average* response in particular makes it less biased or even the most unbiased choice for the group as a whole is a common misunderstanding though.  But for most scenarios, the *average* is an ok / reasonable choice though, for lack of anything better at the moment. :slightly_smiling_face: 

> As mentioned by Thijs on the MRtrix forums: "In a way, the response function is the unit of your FOD"

Yep, that seems to help explain it to most people in practice I've found.  In this way, most people realise that using different response functions between subjects will make the comparison of the FODs confusing.  Using a single unique response (per tissue type) simply means that *all* possible differences end up in the FOD.  How to interpret that, is still up to the user (and context), but at least we can say with confidence that all differences are captured in the FOD(s per tissue type).

Finally, about this:

> Some other steps would, in theory, be needed as well (i.e. bias field correction on the data before giving it as input to TractSeg or mtnormalise the msmt-csd outputs of TractSeg).

Yes, definitely the case.  The easiest way to cover most worries here, is `mtnormalise`.  That doesn't work for single-tissue CSD though; but it *does* work quite well for 2-tissue CSD, which you can always perform on single-shell +b=0 data in any case.  Chatting to @wasserth at OHBM, I understand there's a basic kind of intensity normalisation in the TractSeg pipeline, to make sure the peak amplitudes fed to TractSeg are in a more controlled range / controlled order of magnitude.  In principle, you could replace this step with `mtnormalise`, as long as you always have at least the 2 tissue types (WM/CSF) for single-shell data. `mtnormalise` also brings it to a standardised intensity level / magnitude.  (but you might have to retrain TractSeg to work for that range, if it's not close enough already... but here I'm not the expert at all of course :wink: ).  One particular little hidden pitfall to watch out for though: running MSMT-CSD on single-shell + b=0 data and asking it for the full 3-tissue set of WM-GM-CSF, will automagically give you the WM-CSF fit, with the GM volume being very close to zero everywhere (apart from numerical imprecisions).  That would make it tempting to make the pipeline always do that anyway, but the hidden pitfall is that `mtnormalise` will not play well with this scenario at all; such an artificial GM volume will throw it off very easily.  Providing it instead with only WM-CSF when those are the only 2 tissue types that are really present is the safe and correct choice there.

Ok, that's become quite a lot of future reference here... :stuck_out_tongue:  But I have to say: TractSeg is a *really* neat piece of work.  I've heard quite a few people now already, like @chamberm here, for whom it performed very well on a range of different data; that's actually really cool, I think.

**Comment by wasserth** [comment]
Thank you Thijs for explaining all the details.  
TractSeg is normalizing the peaks before feeding them to the model. So TractSeg will work well without `mtnormalise`. But when doing any quantiative analysis on the peak amplitudes `mtnormalise` should definitely be used as pointed out by you.

**Comment by thijsdhollander** [comment]
> TractSeg is normalizing the peaks before feeding them to the model. So TractSeg will work well without `mtnormalise`.

Yep, makes full sense (also, you're the expert here :wink: ).  It's in many ways good that it does work (well) like this: it shows in some way that TractSeg has a degree of robustness / flexibility about it as well.  One other main job of `mtnormalise` is also the bias field correction; I reckon the presence of a *strong* (but that's relative) bias field might throw off TractSeg at some point.  But a basic level of bias field correction can also be done in the pre-processing stage as well of course (e.g. using ANTs' N4).

So all good; I'm definitely not worried about the performance of TractSeg itself: so far it seems to do a great job in a wide range of conditions. The ultimate challenge will probably be pathologies of different kinds; it'd be really cool to see how far it can be taken!
