### ISSUE TITLE
TractSet for DSI

### ISSUE THREAD

**Issue by MinCW** [MIC-DKFZ/TractSeg#7]
Dear TractSeg Developers:
  Thanks for the wonderful new tool.
  May I know if TractSeg is suitable for DSI? If so, any tweaks are needed?
  Thanks.

Min

**Comment by wasserth** [comment]
Hi Min, 
did you mean Diffusion Spectrum Imaging by DSI? TractSeg needs as input 3 peaks per voxel (in the format of MRtrix: https://mrtrix.readthedocs.io/en/latest/reference/commands/sh2peaks.html; or look at the file tractseg/examples/Diffusion_mrtrix_peaks.nii.gz). If you can extract those peaks from your DSI signal you can try to run TractSeg. However, I do not know how good the results will be as the peaks from DSI might look different than the peaks from normal diffusion MRI which TractSeg was trained on.

**Comment by soichih** [comment]
I was seeing the following error message.

```
+ TractSeg -i dwi.nii.gz --raw_diffusion_input --csd_type csd --output_type tract_segmentation --keep_intermediate_files --postprocess --nr_cpus 8 -o .
INFO: font search path ['/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/ttf', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/afm', '/usr/local/lib/python2.7/dist-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
INFO: generated new fontManager
dwi2response: [ERROR] Command failed: mrconvert /media/data/brlife/workdirs/5ddca099e801c94fab7d50fb/5ddd5f67e801c917dc7d57a3/dwi.nii.gz - -strides 0,0,0,1 -fslgrad /media/data/brlife/workdirs/5ddca099e801c94fab7d50fb/5ddd5f67e801c917dc7d57a3/dwi.bvecs /media/data/brlife/workdirs/5ddca099e801c94fab7d50fb/5ddd5f67e801c917dc7d57a3/dwi.bvals | dwiextract - /media/data/brlife/workdirs/5ddca099e801c94fab7d50fb/5ddd5f67e801c917dc7d57a3/dwi2response-tmp-RWY2QJ/dwi.mif -singleshell -no_bzero (dwi2response:84)
dwi2response: Output of failed command:
              dwiextract: [ERROR] DWI volumes could not be classified into b-value shells; gradient encoding may not represent a HARDI sequence

```

which was caused by feeding DSI dwi data to TractSeg.

> If you can extract those peaks from your DSI signal you can try to run TractSeg.

Could you point me to any information on how to do this? I've looked at this paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5021685/) but I couldn't quite figure out how to run it (I've opened a github issue there also https://github.com/frankyeh/DSI-Studio/issues/39)

**Comment by wasserth** [comment]
I have not worked with DSI sequences before. Therefore unfortunately I can not tell you how to convert a DSI sequence to a peak image. Using `--raw_diffusion_input` is definitely not gonna work because this is calling MRtrix CSD which is expecting a HARDI sequence. You will to extract the peaks yourself before feeding them to TractSeg.
