### ISSUE TITLE
How can I get the trackings from the bundle masks that are predicted from my model?

### ISSUE THREAD

**Issue by luqily** [MIC-DKFZ/TractSeg#81]
Hi, I am sorry to bother you again.
I have gotten the bundle masks from my own model. And how can I get the trackings from them?

**Comment by wasserth** [comment]
Just look into the documentation. There is a detailed description. It's not difficult: https://github.com/MIC-DKFZ/TractSeg#create-bundle-specific-tractograms

**Comment by luqily** [comment]
> Just look into the documentation. There is a detailed description. It's not difficult: https://github.com/MIC-DKFZ/TractSeg#create-bundle-specific-tractograms

Thanks for your reply.
But I only have trained the model for `tract_segmentation`. I don't have `endings_segmentation` and `TOM`. Can I use this to get the trackings?

**Comment by wasserth** [comment]
If you want to run with your own training data, you have to retrain your model for those as well. This is a bit more complicated because you first have to preprocess the training streamlines to get endings masks and peak maps for training. 
For endings segmentations see this code: `tractseg/tractseg/libs/create_endpoints_mask_with_clustering.py`.
For peaks maps see this issue: https://github.com/MIC-DKFZ/TractSeg/issues/82

**Comment by luqily** [comment]
> If you want to run with your own training data, you have to retrain your model for those as well. This is a bit more complicated because you first have to preprocess the training streamlines to get endings masks and peak maps for training.
> For endings segmentations see this code: `tractseg/tractseg/libs/create_endpoints_mask_with_clustering.py`.
> For peaks maps see this issue: #82

Thanks so much!
