### ISSUE TITLE
Tractometry - Identify specific end regions

### ISSUE THREAD

**Issue by JoaoPaulo100** [MIC-DKFZ/TractSeg#95]
Hello Jakob,

Thanks again for this great tool! After using tractometry, I found that specific segments of the tract were significantly different between my groups. Is there a way to identify the specific end regions of these segments? 

Thanks!
João Paulo

**Comment by wasserth** [comment]
Unfortunately this is not easily possible so far. I will try to make code available to plot the segments onto the streamlines in a 3D plot in the future.

**Comment by JoaoPaulo100** [comment]
Thanks! We tried to create these plots, but it's more challenging than we expected. Thank you for all of the hard work!

**Comment by skebaas** [comment]
Hello Jakob,

Joao and I added edited the Tractometry script in order to output the centroid of each bundle into a .json file.  When plotting these points into Fiber navigator some centroids lined up very well, while others were pretty far off track.  I was wondering if you had a better idea on how to do this using the streamlines.

Thank you,
Alex

**Comment by wasserth** [comment]
I would use dipy to get the centroid and then save it trk file. I guess this is similar to what you did? Saving a streamline/centroid into a json file might be problematic as it does not save the image geometry in the header.

**Comment by wasserth** [comment]
I just  added code to plot the tractometry FA results on top of 3D streamlines for each bundle. See the tractometry tutorial for more details.

**Comment by JoaoPaulo100** [comment]
Thanks, Jakob! It looks great! Do you know if we can use this tool to display pvalues obtained from different statistical software?

**Comment by wasserth** [comment]
Using the pvalues obtained from a different statistical software does not directly work. You would have to adapt the code for that.
Plotting  the pvalues produced by TractSeg instead of the FA is quite easy: Just uncomment line 203 in `bin/plot_tractometry_results` (you need the newest master for that).

**Comment by JoaoPaulo100** [comment]
Thanks! Using plot_tractometry_results, I got the plots with alphaFWE, but I got this error for plot3D:

ValueError: Could not find: /tractseg_output/TOM_trackings_filt_prob/CG_left.trk

I checked the code, but I'm not sure when the 'TOM_trackings_filt_prob' directory should have been created. Did I skip any steps here?

Thanks,
João Paulo

**Comment by wasserth** [comment]
That was a bug. Sorry. Now it is looking for `.../TOM_trackings/...` per default or you can specify it manually when calling `bin/plot_tractometry_results`.

**Comment by skebaas** [comment]
Thank you again Jakob for all of your help.  The segmentation looks great, but there seems to be an issue the bundle being mapped to the brain template.  Here is what we are getting. 
![ATR_Left](https://user-images.githubusercontent.com/54587831/73203523-3a7df380-410b-11ea-8d5c-5e390365a7c4.PNG)

Best,
Alex

**Comment by wasserth** [comment]
Are you plotting the bundles which were generated by TractSeg? Or did you do any custom processing of the bundles before plotting them? What tracking format are you using (when calling `Tracking`) ?

**Comment by JoaoPaulo100** [comment]
We are using Tractseg bundles and did not make any custom processing before plotting. This is the command line:

Tracking -i peaks.nii.gz --nr_fibers 10000 --tracking_format tck

Should we add something else?

**Comment by wasserth** [comment]
What is the affine of your brain mask? It might work better if your images are in MNI space.

**Comment by skebaas** [comment]
Hello Jakob,
Your suggestion worked and we are now having it correctly projected onto the MNI brain!  We made a slight mod in the plot_tractometry_results script to force our list of P-values that we have and set it equal to the metric.  It is working for now, but we noticed that the last number in the metric list is not being displayed.

**Comment by wasserth** [comment]
I am happy to hear that it works.
The streamlines are subdivided into 100 segments. Since the first and last element are not so reliable those are removed. The result of Tractometry are therefore 98 values.
For plotting we have to get 100 elements again. So the first and last element of the 98 values are duplicated.
This happens in line 351 in `tractseg/libs/plot_utils.py`:  
`metrics = np.array([metrics[0]] + metrics + [metrics[-1]])`  

You could adapt this if needed.

**Comment by JoaoPaulo100** [comment]
Thank you, Jakob! We really appreciate all of your comments.
